export const baseUrl = ''
export const emailUrl = 'http://api-oa-email.xueerqin.net'
export const payrollUrl = 'http://api-oa-salary.xueerqin.net'
export const baseUrl2 = 'http://public-api.xueerqin.net'
export const noticeUrl = 'http://api-notice.xueerqin.net'
